# Use Task to define tasks and run them locally or in CI
# For more information about Task, see https://taskfile.dev/#/usage?id=usage
version: '3'

# Define variables to use in tasks
vars:
  GIT_COMMIT:
    desc: "The git commit hash of the current commit."
    sh: git rev-parse --short HEAD
  GIT_TAG:
    desc: "The git tag of the current commit."
    sh: git describe --tags --abbrev=0 2>/dev/null || echo "latest"
  GIT_TAG_COMMIT:
    desc: "The last tagged commit."
    sh: git rev-list --abbrev-commit --tags --max-count=1
  GIT_BUILD:
    desc: "The number of commits since the last tag."
    sh: echo '{{if ne .GIT_COMMIT .GIT_TAG_COMMIT}}-{{.GIT_COMMIT}}{{end}}'
  GIT_DIRTY:
    desc: "Whether the git repository is dirty."
    sh: git diff --quiet || echo "+dirty"
  VERSION:
    desc: "The version of the image."
    sh: echo '{{.GIT_TAG}}{{.GIT_BUILD}}{{.GIT_DIRTY}}'
  BUILD_DATE:
    desc: "The date the image was built."
    sh: date '+%d-%m-%Y %H:%M:%S'
  BUILD_FOLDER:
    desc: "The folder where the build is happening. Current folder/build"
    sh: echo "build"

# Import tasks from other files
includes:
  go: ./.task/go.taskfile.yml

# Define tasks
tasks:
  info:
    desc: "Display information about the project."
    cmds:
      - echo "version is ({{.VERSION}})"
      - echo "build date is ({{.BUILD_DATE}})"
    silent: true
