// Code generated by tagsvar. DO NOT EDIT.

package testdata

// File: ../../.testdata/user.go

// Struct: User
// User is a struct that represents a user
const (
	// Tag: json
	JsonUserId   = "id"
	JsonUserName = "name"

	// Tag: xml
	XmlUserId   = "id"
	XmlUserName = "name"

	// Tag: gorm
	GormUserId   = "id"
	GormUserName = "name"
)
